package SyntaxAnalyzer;

public enum SyntaxError {
    InvalidConstantDeclaration,
    InvalidVariableDeclaration,
    UninitializedConstant,
    UninitializedVariable,
    DuplicateSymbol,
    SymbolNotFound,
    ExpectIdentifier,
    ExpectInt32,
    ExpectCorrectSeparator,
    ExpectLeftParenthesis,
    ExpectRightParenthesis,
    ExpectType,
    ExpectReturnType,
    InvalidFunctionDeclaration,
    MissingParameter,
    MissingFunctionBody,
    InvalidSentenceSequence,
    InvalidExpression,
    InvalidFactor,
    InvalidIfStatement,
    InvalidWhileStatement,
    InvalidAssignment,
    InvalidReturn,
    ExpectTypeSpecifier,
    InvalidReturnType,
    InvalidScan,
    InvalidPrint,
    InvalidCall,
    InvalidCondition,
    LessArguments,
    MoreArguments,
    AssignToConstant,
    AssignToFunction,
    AssignWithDeclaration,
    MissingMain,
    MissingCondition,
    MissingSemicolon,
    MissingSentence,
    ReturnValueForVoidFunction,
    NoReturnValueForIntFunction,
    NotCallingFunction,
    UnsupportedFeature,
    UnreadError,
    UnknownError // Only for test
}
